# netlify.toml - Configuración para deploy de PULSE HUB

[build]
  # Base directory apunta a la raíz del monorepo
  base = "/"

  # Build command: usar el script de build del monorepo que maneja shared + web
  command = "npm run build:web"

  # Directorio de publicación
  publish = "apps/web/.next"

# Configuración de Netlify Functions
[functions]
  directory = "apps/web/netlify/functions"
  node_bundler = "esbuild"

# Variables de entorno para producción
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.pulse-hub-1.netlify.app"
  NEXT_PUBLIC_APP_NAME = "PULSE HUB"
  NODE_VERSION = "20"
  # No establecer NODE_ENV=production durante el build para que instale devDependencies
  NPM_FLAGS = "--include=dev"
  # Variables para Netlify Functions (configurar en Netlify UI):
  # OPENAI_API_KEY - API key de OpenAI
  # OPENAI_MODEL - Modelo a usar (default: gpt-4o-mini)
  # OPENAI_MAX_TOKENS - Máximo de tokens (default: 1000)
  # CODA_API_KEY - API key de Coda
  # CODA_DOC_ID - ID del documento en Coda
  # CODA_TABLE_ID - ID de la tabla en Coda

# Variables de entorno para deploy previews
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://pulse-hub-1.netlify.app"
  NEXT_PUBLIC_APP_NAME = "PULSE HUB"
  NODE_VERSION = "20"

# Variables de entorno para branch deploys
[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://pulse-hub-1.netlify.app"
  NEXT_PUBLIC_APP_NAME = "PULSE HUB"
  NODE_VERSION = "20"

# Plugin de Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
